### ISSUE TITLE
@media block gives syntax error

### ISSUE THREAD

**Issue by crisp-tweakers** [MyIntervals/PHP-CSS-Parser#352]
```
@media (min-width: 1220px) {
  div { width:auto; }
}
```

gives an "Syntax error in CSS: Identifier expected. Got “}” [line no: 3]"

This looks like a regression in version 8.4.0 - I'm suspecting https://github.com/sabberworm/PHP-CSS-Parser/pull/162

**Comment by michaelhue** [comment]
I can confirm the issue. We also had errors in `@keyframe` rules.

**Comment by mikkorantalainen** [comment]
Is there any progress with this? I tried to upgrade from 8.3.0 to latest code from `composer` which claims to be be "8.4.0" even though no such version has been released yet in GitHub. That version fails to parse even simple media queries like

```
@media print
{
	html
	{
		background: white;
		color: black;
	}
}
```
so I have to revert back to 8.3.0 and apply PHP 8 compatibility fixes manually.

**Comment by crisp-tweakers** [comment]
This issue still seems to be present in version 8.5.0 so unfortunately we still can't update to the latest version.

However it is good to see that this library gets some much needed maintenance and care. As far as I know it is the only PHP-based CSS parser/validator available. Keep up the good work, it is highly appreciated!

**Comment by JakeQZ** [comment]
I can only reproduce this with strict parsing (`Settings::beStrict()`).

I think the mistake is in https://github.com/MyIntervals/PHP-CSS-Parser/pull/162/commits/134f4e62fe8ab9f316425f3c0f480b3f4f52d804 with the change to `CSSList.php`.

The logic has not been correctly preserverd.  When a `}` is encountered and `bIsRoot` is `false`, it should not fail, but merely return `null` to indicate the end of the list.  But now it's throwing an exception if strict parsing is set.

This was picked up by turning on strict parsing in the tests.  So maybe we should be running the tests with strict parsing set (actually I think both flavours).

@sabberworm, does my analysis make sense?

**Comment by JakeQZ** [comment]
> @sabberworm, does my analysis make sense?

It seems that this bit of code should not have been changed at all for #162.  After refactoring, it has the same logic as before, so I we may as well change it back, with an additional comment about what returning `null` means.

**Comment by VaguelyOnline** [comment]
Having the same issue here. The rule it's failing on for us is: 

@media only screen and (max-width: 768px) {
    .body-signin .content {
        margin-top: 120px;
    }
}

Should I just hang-tight and do a composer update in the next couple of days?

**Comment by JakeQZ** [comment]
> Should I just hang-tight and do a composer update in the next couple of days?

I think we are planning to make an 8.5.1 release with this fix soon.

The other option you have is to not use [strict parsing](https://github.com/MyIntervals/PHP-CSS-Parser?tab=readme-ov-file#strict-parsing).  In future major releases we plan to deprecate this and replace it with a logging option.

**Comment by VaguelyOnline** [comment]
> I think we are planning to make an 8.5.1 release with this fix soon.
> 
> The other option you have is to not use [strict parsing](https://github.com/MyIntervals/PHP-CSS-Parser?tab=readme-ov-file#strict-parsing). In future major releases we plan to deprecate this and replace it with a logging option.

Thanks for the info. Really appreciate the transparency and the utility of the project. Thanks for the hard work.

**Comment by oliverklee** [comment]
I've just tagged V8.5.1 and published the release: https://github.com/MyIntervals/PHP-CSS-Parser/releases/tag/v8.5.1
