### ISSUE TITLE
Mark the public class constants as `@internal`

### ISSUE THREAD

**Issue by oliverklee** [MyIntervals/PHP-CSS-Parser#471]
Those class constants are not intended to be accessed from outside this package.

**Comment by sabberworm** [comment]
Do they need to be `public` at all?

**Comment by oliverklee** [comment]
> Do they need to be `public` at all?

Some of them, yes, as they are either part of an interface (where only `public const`s are possible), or because they are accessed from another class.

**Comment by JakeQZ** [comment]
> Do they need to be `public` at all?

Setting the visibility of class constants (e.g. with `private const`) has only been possible since PHP 7.1.  So it's only now possible to clear this up since dropping the older PHP versions.
