### ISSUE TITLE
Deprecate `expandShorthands`/`createShorthands`/`create*Shorthand`/`expand*Shorthand`

### ISSUE THREAD

**Issue by oliverklee** [MyIntervals/PHP-CSS-Parser#512]
https://github.com/MyIntervals/PHP-CSS-Parser/issues/510#issuecomment-1972628778

Expanding and creating the shorthand notation is out of scope for this library. So we should ~~remove the functionality, make all the corresponding methods a no-op and~~ mark ~~them~~ these methods as `@deprecated #511 will be removed in version 10`.

**Comment by JakeQZ** [comment]
We could provide a link in the readme to a tag for the last release which includes the functionality, to help anyone who wants to include it in their own project, and/or encourage someone to build it into a separate package.

**Comment by ziegenberg** [comment]
One deprecation at a time:

- [ ] #558
- [ ] #566
- [ ] #567
- [ ] #568
- [ ] #569
- [ ] #570
- [ ] #571
- [ ] #572
- [ ] #573
- [ ] #574
- [ ] #575
- [ ] #578

**Comment by sabberworm** [comment]
@ziegenberg IMHO you could have put the deprecations into a single PR instead of doing a new PR for every single method. Thanks a lot for your contributions, though.

**Comment by oliverklee** [comment]
> IMHO you could have put the deprecations into a single PR instead of doing a new PR for every single method.

@ziegenberg talked/wrote about this, and I requested them to be single PRs. This allows for smaller PRs and allows us to easily revert single things that haven't worked out.

**Comment by ziegenberg** [comment]
I surely would have put them into one PR. Would have been much easier and would require a *lot* less rebasing, namely 0.

That's another thing to put into the CONTRIBUTING.md, together with all other kinds of policies.

**Comment by sabberworm** [comment]
It seems @oliverklee and I disagree about what is an atomic change…

**Comment by sabberworm** [comment]
I guess a compromise would have been to make it a single PR but one commit for each change. That would have made them revertable without all the drawbacks.

**Comment by ziegenberg** [comment]
> Then we would have had a merge commit, and I find a linear history really helpful.
> 
> For cases like this, I'd be fine with having separate PRs for the deprecations and a follow-up PR to add the changelog entries. This would help avoid the merge conflicts and the need for a rebase. Would that be helpful for you, @ziegenberg?

Yes, that would be helpful next time.

This time, Whether I rebase this pile of PRs or collect all changelog entries from every PR, package it into a new PR and adjust all PRs, it makes no difference in the work I have to do.

In either case, make it a policy and put it into `CONTRIBUTING.md` for others to follow.

**Comment by ziegenberg** [comment]
Can be closed now.

**Comment by oliverklee** [comment]
Thanks a lot, @ziegenberg! ❤️
