### ISSUE TITLE
Add a Composer Script for PHP linting and use it on CI

### ISSUE THREAD

**Issue by oliverklee** [MyIntervals/PHP-CSS-Parser#551]
Also lint `config/` in order to catch e.g. language features that are not supported in all the PHP versions we support.

@ziegenberg Would you be willing to tackle this one?

**Comment by ziegenberg** [comment]
Would you be ok with introducing [PHPCSStandards/PHP_CodeSniffer](https://github.com/PHPCSStandards/PHP_CodeSniffer/)?

**Comment by oliverklee** [comment]
I think we have a misunderstanding here. :-)

This is about the PHP syntax linting using `php -l` (which we [already have](https://github.com/MyIntervals/PHP-CSS-Parser/blob/main/.github/workflows/ci.yml#L14), but not as a Composer script).

For style checking, we're already using [PHP-CS-Fixer](https://github.com/MyIntervals/PHP-CSS-Parser/blob/main/composer.json#L72). I'd prefer to keep this (as this project seems to be maintained a lot more actively than PHP_CodeSniffer). And I'd prefer to not use both tools in the same project as in my experience it can be quite cumbersome to fix situations where the styles required by both tools disagree with each other, resulting in a style whack-a-mole. ;-)

**Comment by ziegenberg** [comment]
Can this be changed so that PHP-CS-Fixer is also installed via Composer? PHP-CSS-Parser would be the only project I'm working on to require phive for installing dev tools. With Composer we would also benefit from simpler CI tasks and dependabot would inform us about updates.

_Sidenote: I'm not sure how the impression was created that PHP_CodeSniffer is not as well maintained. I can see regular releases [^1]. Also, PHP-CS-Fixer only claims PHP 7.4+ support[^2]._


[^1]: https://github.com/PHPCSStandards/PHP_CodeSniffer/releases
[^2]: https://github.com/PHP-CS-Fixer/PHP-CS-Fixer?tab=readme-ov-file#supported-php-versions

**Comment by oliverklee** [comment]
> Can this be changed so that PHP-CS-Fixer is also installed via Composer? 

Unfortunately not (at least at the moment). We want to have the latest version to make use of the (WIP) PER-2 ruleset, and having friendsofphp/php-cs-fixer as a Composer (dev) dependency would make this project uninstallable in PHP 7.2 and 7.3 (as friendsofphp/php-cs-fixer  requires PHP >= 7.4).

As soon as we've dropped support for PHP 7.4, we can switch friendsofphp/php-cs-fixer from PHIVE to Composer. (This most probably won't happen for version 9. For version 10, we still need to talk about and decide on the system requirements. As this is a library, we tend to keep supporting old PHP versions for quite some time, though.)

**Comment by ziegenberg** [comment]
Do we need to lint with all supported PHP versions, or shouldn't just the lowest and highest supported versions be enough to catch everything?

**Comment by oliverklee** [comment]
> Do we need to lint with all supported PHP versions, or shouldn't just the lowest and highest supported versions be enough to catch everything?

With all versions. This won't allow us to catch more problems, but it will help pin down which with which exact PHP version the problem occurs. (Also, PHP linting is really fast.)
