### ISSUE TITLE
Use single-quoted string literals whenever possible

### ISSUE THREAD

**Issue by JakeQZ** [MyIntervals/PHP-CSS-Parser#640]
The additional features of double-quoted strings create more potential for mistakes, and might be slower for PHP to parse.

Hopefully there's a PHP-CS-Fixer rule for this.

**Comment by oliverklee** [comment]
There indeed is: https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/doc/rules/string_notation/single_quote.rst

**Comment by oliverklee** [comment]
For the record, this has no impact on performance: https://www.npopov.com/2012/01/09/Disproving-the-Single-Quotes-Performance-Myth.html

**Comment by JakeQZ** [comment]
> For the record, this has no impact on performance: https://www.npopov.com/2012/01/09/Disproving-the-Single-Quotes-Performance-Myth.html

I thought so, since I could think of an implementation which would not impact performance.
