### ISSUE TITLE
Deprecate `Parser::setCharset/getCharset`

### ISSUE THREAD

**Issue by oliverklee** [MyIntervals/PHP-CSS-Parser#681]
Deprecate it in 8.x and remove it in 9.0.

**Comment by JakeQZ** [comment]
Shouldn't we deprecate it in 9.0 and remove it in 10.0?  8.x is already released.

**Comment by oliverklee** [comment]
Once merged, I'd like to backport this deprecation to 8.x so the deprecation annotation will be in the hopefully-to-be-released-soon 8.7, which would allow us to remove the deprecated things in 9.0.

I'd also like to backport the other deprecations if possible (#696) for the same reason.

**Comment by JakeQZ** [comment]
> I'd like to backport this deprecation to 8.x so the deprecation annotation will be in the hopefully-to-be-released-soon 8.7, which would allow us to remove the deprecated things in 9.0.

OK.  This is consistent with [Semantic Versioning](https://semver.org/#spec-item-7)
